version: '3'

services:
  flask:
    build:
      context: ./app
    depends_on:
      - redis
    ports:
      - 80:80
    networks:
      - inception
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - inception

networks:
  inception: