version: '3'

services:
  flask:
    container_name: flask
    build: ./app
    depends_on:
      - redis
    ports:
      - 80:80
    restart: always
    networks:
      - inception

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - inception

networks:
  inception: